# Generated by Django 5.0.6 on 2024-06-21 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chkboxoption',
            name='optionname',
        ),
    ]
